server:
  port: 0

eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: '12345678'
    platform: mysql
    url: jdbc:mysql://localhost/books?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      hbm2ddl:
        auto: update

